version: '3.0'

volumes:
  database_data: {}

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.production
    depends_on:
      - database
    ports:
      - '8081:8081'
  database:
    hostname: mongo
    container_name: mongo
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=resume-creator
    volumes:
      - database_data:/data/db
    ports:
      - '27018:27017'
