version: '3.0'

volumes:
  database_data: {}

services:
  web:
    command: npm run dev:start
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - '8081:8081'
  database:
    hostname: mongo
    container_name: mongo
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=resume-creator
    #      - MONGO_INITDB_HOST=127.0.0.1
    #      - MONGO_INITDB_PORT=27017
    volumes:
      - database_data:/data/db
    ports:
      - '27018:27017'
